using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using TravelPlanner.Api.DTOs.Requests;
using TravelPlanner.Api.DTOs.Responses;
using TravelPlanner.Api.Exceptions;
using System.Diagnostics;
using TravelPlanner.Api.Logging;

namespace TravelPlanner.Api.Services.GrokAIService
{
    public class GrokAIService : IGrokAIService
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;
        private readonly AIRequestLogger _aiRequestLogger;

        public GrokAIService(HttpClient httpClient, IConfiguration configuration, AIRequestLogger aiRequestLogger)
        {
            _httpClient = httpClient;
            _configuration = configuration;
            _aiRequestLogger = aiRequestLogger;

            _httpClient.Timeout = TimeSpan.FromMinutes(1);
        }

        // Creates destination suggestions based on the user's travel preferences and returns a structured response
        public async Task<DestinationResponseDto> GetDestinationsAsync(DestinationRequestDto request)
        {
            var prompt =
                $"Suggest exactly 3 travel destinations from Stockholm for a budget of {request.Budget} SEK, " +
                $"{request.Days} day(s), departure date {request.DepartureDate:yyyy-MM-dd}. " +
                "Return only the city names separated by commas. No extra text.";

            var aiText = await SendPromptToGrokAsync(prompt);

            return new DestinationResponseDto
            {
                Summary = "AI-generated destination suggestions.",
                Destinations = aiText.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Take(3).ToList(),
                QualityNotes = "Generated by Grok AI.",
                TraceId = Guid.NewGuid().ToString()
            };
        }

        // Creates a travel plan based on the user's request and returns a structured response
        public async Task<TravelPlanResponseDto> CreateTravelPlanAsync(TravelPlanRequestDto request)
        {
            var prompt = $@"You are a travel planner.

                Create a travel plan for {request.Destination}.

                Return ONLY valid JSON.
                Do not use markdown.
                Do not add text before or after the JSON.

                The JSON must match this structure exactly:

                {{
                  ""selectedDestination"": ""{request.Destination}"",
                  ""estimatedCost"": 0,
                  ""currency"": ""SEK"",
                  ""travelPlanText"": [
                    ""Visit one famous historical place"",
                    ""Visit one nature or view location"",
                    ""Try local food"",
                    ""Include one sport or outdoor activity"",
                    ""Include one relaxing activity""
                  ],
                  ""qualityNotes"": [
                    ""Exemple limitation 1"",
                    ""Exemple limitation 2"",
                    ""Exemple limitation 3""
                  ],
                  ""summary"": ""Short summary, maximum two sentences."",
                  ""traceId"": """"
                }}

                Rules:
                - travelPlanText must contain exactly 5 short points.
                - qualityNotes must contain exactly 3 short points.
                - estimatedCost must be less than or equal to user's budget.
                - estimated cost must be a number only, without SEK or any text.
                - estimatedCost must be a realistic estimate for the destination and activities.
                - never return an estimatedCost higher than the user's budget.
                - currency must always be 'SEK'.
                - qualityNotes must contain realistic destination-specific limitations or considerations.
                ";

            var aiText = await SendPromptToGrokAsync(prompt);

            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };

            var result = JsonSerializer.Deserialize<TravelPlanResponseDto>(aiText, options);

            result!.TraceId = Guid.NewGuid().ToString();

            return result;
        }

        // Sends  a prompt to Grok AI and returs the AI response
        private async Task<string> SendPromptToGrokAsync(string prompt)
        {
            var apiKey = _configuration["GrokAI:ApiKey"];
            var baseUrl = _configuration["GrokAI:BaseUrl"];
            var endpointPath = _configuration["GrokAI:EndpointPath"];

            var traceId = Guid.NewGuid().ToString();
            var stopwatch = Stopwatch.StartNew();

            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", apiKey);

            var body = new
            {
                model = "grok-4.3",
                messages = new[]
                {
            new { role = "system", content = "You are a helpful travel planning assistant." },
            new { role = "user", content = prompt }
        }
            };

            var json = JsonSerializer.Serialize(body);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            HttpResponseMessage response;
            string responseText;

            try
            {
                response = await _httpClient.PostAsync($"{baseUrl}{endpointPath}", content);
                responseText = await response.Content.ReadAsStringAsync();
                stopwatch.Stop();
            }
            catch (TaskCanceledException)
            {
                stopwatch.Stop();
                _aiRequestLogger.LogTimeout(stopwatch.ElapsedMilliseconds, traceId);
                throw AppException.Timeout();
            }
            catch (HttpRequestException)
            {
                stopwatch.Stop();
                _aiRequestLogger.LogFailure(0, stopwatch.ElapsedMilliseconds, traceId);
                throw AppException.UnexpectedError();
            }

            if (!response.IsSuccessStatusCode)
            {
                _aiRequestLogger.LogFailure((int)response.StatusCode, stopwatch.ElapsedMilliseconds, traceId);

                if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized ||
                    response.StatusCode == System.Net.HttpStatusCode.Forbidden ||
                    response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    throw AppException.AuthenticationFailed();
                }

                if ((int)response.StatusCode == 429)
                {
                    throw AppException.RateLimitReached();
                }

                throw AppException.UnexpectedError();
            }

            _aiRequestLogger.LogSuccess((int)response.StatusCode, stopwatch.ElapsedMilliseconds, traceId);

            using var document = JsonDocument.Parse(responseText);

            return document.RootElement
                .GetProperty("choices")[0]
                .GetProperty("message")
                .GetProperty("content")
                .GetString() ?? string.Empty;
        }

    }
}

